name: Go

on:
  push:

jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - run: go test -v ./pkg/...
